[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:memcached]
command=/usr/bin/memcached -u memcache -m 64
autostart=true
autorestart=true
